name: Share data between jobs
on: [push]
jobs:
  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > sum.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v1
        with:
          name: homework
          path: sum.txt
  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v1
        with:
          name: homework
      - shell: bash
        run: |
          expr $(cat homework/sum.txt) \* 9 > multiply.txt
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v1
        with:
          name: homework1
          path: multiply.txt
  job_3:
    name: Display results
    needs: job_2
    runs-on: macOS-latest
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v1
        with:
          name: homework1
      - name: Print the final result
        shell: bash
        run: |
          value=`cat homework1/multiply.txt`
          echo The result is $value









